import type { CorpusCase } from "./types";

/**
 * The corpus, built by specification reduction.
 *
 * For each case the detailed specification was written first, then reduced to the short
 * request a real person would actually type. Every ground-truth decision is therefore a
 * statement that is present in `fullSpec` and absent from `request`. This matters: the
 * ground truth was fixed before any detection strategy was designed, so no arm's mechanism
 * had any influence over what counts as a decision.
 *
 * Decision content is grounded in how these domains actually operate — real cancellation
 * windows, real proration conventions, real reservation semantics — rather than invented
 * edge cases, so that "a competent implementer must decide this" is a claim about the
 * domain rather than about the author's imagination.
 */

const booking: CorpusCase = {
  id: "booking-massage",
  domain: "booking",
  request:
    "Build a booking system for a massage centre. Clients choose a therapist, a treatment and a time, " +
    "and book online. Staff can see the day schedule.",
  fullSpec: [
    "Clients book a named therapist for a named treatment at a start time.",
    "Slot allocation is first-commit-wins: the losing concurrent booking is rejected with an offer of the nearest free slot.",
    "Each treatment has a turnaround buffer of 15 minutes after it, which is unbookable.",
    "Bookings may be made no more than 60 days ahead and no less than 2 hours ahead.",
    "Cancellation is free until 24 hours before the appointment.",
    "Cancelling inside 24 hours forfeits 50 percent of the price; a no-show forfeits 100 percent.",
    "Rescheduling inside 24 hours is treated as a cancellation plus a new booking.",
    "If payment is captured but the slot is lost, the payment is voided automatically and the client is told.",
    "Repeated submission of the same booking form within 10 minutes creates one booking, not several.",
    "Clients see only bookable slots, never the full therapist diary.",
    "When a therapist is deactivated, their future bookings are cancelled and clients are notified with a refund.",
    "All times are shown in the local timezone of the centre regardless of the client device.",
    "Staff may overbook a therapist manually; client-facing booking may not.",
  ].join("\n"),
  decisions: [
    {
      id: "bk-1",
      question: "When two clients try to book the same therapist and time at the same moment, who gets it?",
      options: [
        "First commit wins, the other is rejected",
        "Both are held pending staff resolution",
        "The slot is double-booked",
      ],
      discriminator: "Two clients submit a booking for Ana at 14:00 within the same second.",
      category: "concurrency",
      consequence: "Determines whether a uniqueness constraint and a rejection path exist at all.",
    },
    {
      id: "bk-2",
      question: "How late may a client cancel without penalty?",
      options: ["Any time", "24 hours before", "6 hours before"],
      discriminator: "A client cancels 3 hours before their appointment.",
      category: "temporal",
      consequence: "Decides whether a deadline is stored and evaluated at all.",
    },
    {
      id: "bk-3",
      question: "What happens to money when a client cancels late or does not turn up?",
      options: ["Full refund", "Partial forfeit", "No refund", "Credit for future use"],
      discriminator: "A client who paid in advance cancels 3 hours before.",
      category: "money",
      consequence: "Determines whether refunds, partial captures and credit balances exist.",
    },
    {
      id: "bk-4",
      question: "Is there unbookable turnaround time between two appointments for the same therapist?",
      options: ["None, back to back", "A fixed buffer", "A per-treatment buffer"],
      discriminator: "A 60-minute massage ends at 15:00; can another client book 15:00?",
      category: "temporal",
      consequence: "Changes the availability computation, not just the display.",
    },
    {
      id: "bk-5",
      question: "How far ahead, and how close to the start, may a booking be made?",
      options: ["No limits", "A maximum horizon and a minimum notice", "Minimum notice only"],
      discriminator: "A client tries to book a slot starting in 10 minutes, and another 8 months out.",
      category: "boundary",
      consequence: "Without bounds the calendar is infinite and same-minute bookings are accepted.",
    },
    {
      id: "bk-6",
      question: "If payment succeeds but the booking cannot be written, what happens to the money?",
      options: ["Automatically voided", "Held and resolved by staff", "Kept as credit", "Lost silently"],
      discriminator: "The card is charged, then the slot write fails because the slot was just taken.",
      category: "partial_failure",
      consequence: "Determines whether a compensating transaction path is built.",
    },
    {
      id: "bk-7",
      question: "What happens if the client submits the same booking twice?",
      options: ["One booking", "Two bookings", "The second is rejected as a duplicate"],
      discriminator: "The client double-clicks Confirm, or retries after a timeout.",
      category: "idempotency",
      consequence: "Decides whether requests carry an idempotency key.",
    },
    {
      id: "bk-8",
      question: "Do clients see the whole therapist diary or only free slots?",
      options: ["Only bookable slots", "The full diary including who booked", "Free and busy without names"],
      discriminator: "A client opens the availability of Ana for tomorrow.",
      category: "visibility",
      consequence: "A privacy decision about other clients, not a display preference.",
    },
    {
      id: "bk-9",
      question: "What happens to future bookings when a therapist leaves or is deactivated?",
      options: [
        "Cancelled and refunded with notice",
        "Reassigned automatically to another therapist",
        "Left pointing at an inactive therapist",
      ],
      discriminator: "Ana leaves on the 1st; she has 30 appointments booked through the month.",
      category: "lifecycle",
      consequence: "Determines whether deactivation is a flag or a cascading process.",
    },
    {
      id: "bk-10",
      question: "Is rescheduling a distinct operation, or a cancellation followed by a new booking?",
      options: [
        "Distinct, keeps the original terms",
        "Cancel plus rebook, so penalties apply",
        "Free before the deadline, otherwise cancel plus rebook",
      ],
      discriminator: "A client moves a booking from 09:00 to 11:00 tomorrow, two hours before it starts.",
      category: "reversal",
      consequence: "Changes whether the cancellation penalty applies to a move.",
    },
    {
      id: "bk-11",
      question: "Whose timezone are appointment times expressed in?",
      options: ["The local time of the centre", "The device time of the client", "UTC"],
      discriminator: "A client books from a device set to a different timezone.",
      category: "temporal",
      consequence: "Determines whether times are stored with a zone and how they are rendered.",
    },
    {
      id: "bk-12",
      question: "May staff create bookings that violate the client-facing rules?",
      options: ["Yes, staff may overbook", "No, the same rules apply", "Yes with a recorded reason"],
      discriminator: "Reception adds a walk-in on top of an already-booked slot.",
      category: "authority",
      consequence: "Splits validation into two rule sets rather than one.",
    },
  ],
};

const billing: CorpusCase = {
  id: "billing-plan-change",
  domain: "billing",
  request:
    "We need subscription billing for our SaaS. Customers pick a monthly plan, can upgrade or downgrade, " +
    "and get charged automatically. Show them their invoices.",
  fullSpec: [
    "Plans are monthly and charged in advance on the subscription anniversary.",
    "An upgrade takes effect immediately and is charged pro rata for the remainder of the period.",
    "A downgrade takes effect at the end of the current period and no money is returned.",
    "Proration is computed by whole days, rounded to the nearest cent, with the remainder favouring the customer.",
    "A failed payment is retried on days 1, 3 and 7; access is suspended after the third failure and the account is cancelled after 21 days.",
    "Suspended accounts retain their data; cancelled accounts retain data for 30 days.",
    "Cancellation takes effect at period end, the customer keeps access until then, and no partial refund is given.",
    "Repeating a charge request with the same idempotency key never charges twice.",
    "Tax is calculated at the billing address of the customer at the time the invoice is issued.",
    "Invoices are immutable once issued; corrections are issued as credit notes.",
    "Only account owners may change the plan; members may view invoices but not billing details.",
    "A plan change during a failed-payment grace period is refused until the balance is settled.",
  ].join("\n"),
  decisions: [
    {
      id: "bl-1",
      question: "When does an upgrade take effect, and is the remainder of the period charged?",
      options: ["Immediately with proration", "At the next renewal", "Immediately at full price"],
      discriminator: "A customer upgrades on day 10 of a 30-day period.",
      category: "money",
      consequence: "Determines whether proration arithmetic exists at all.",
    },
    {
      id: "bl-2",
      question: "When does a downgrade take effect, and is money returned?",
      options: ["End of period, no refund", "Immediately with credit", "Immediately with a cash refund"],
      discriminator: "A customer downgrades on day 10 of a 30-day period.",
      category: "money",
      consequence: "Refunds and credits are different subsystems; this decides which is needed.",
    },
    {
      id: "bl-3",
      question: "How is a partial period rounded, and who benefits from the remainder?",
      options: [
        "Whole days, rounded to the cent favouring the customer",
        "By the second with banker rounding",
        "Whole months only",
      ],
      discriminator: "A pro-rata amount computes to 7.145 units of currency.",
      category: "money",
      consequence: "Rounding direction is a policy with accounting and legal consequences.",
    },
    {
      id: "bl-4",
      question: "What is the retry schedule for a failed payment, and when is access cut off?",
      options: [
        "No retries, immediate suspension",
        "Scheduled retries then suspension then cancellation",
        "Indefinite retries and never suspend",
      ],
      discriminator: "The card of a customer is declined on the renewal date.",
      category: "partial_failure",
      consequence: "Dunning is a stateful scheduled process, not a single failed call.",
    },
    {
      id: "bl-5",
      question: "What happens to customer data on suspension and on cancellation?",
      options: ["Retained indefinitely", "Retained for a fixed window then deleted", "Deleted immediately"],
      discriminator: "An account is cancelled after 21 days of non-payment.",
      category: "lifecycle",
      consequence: "Data retention is a compliance obligation with a deletion job behind it.",
    },
    {
      id: "bl-6",
      question: "Does a cancelling customer keep access until period end, and is anything refunded?",
      options: ["Access to period end, no refund", "Immediate cutoff with a refund", "Immediate cutoff, no refund"],
      discriminator: "A customer cancels on day 3 of a 30-day period they already paid for.",
      category: "reversal",
      consequence: "Changes both the entitlement check and the refund path.",
    },
    {
      id: "bl-7",
      question: "What prevents a retried charge request from charging twice?",
      options: ["Idempotency keys", "Nothing", "Duplicate detection by amount and time"],
      discriminator: "The billing job times out and is retried after the charge already succeeded.",
      category: "idempotency",
      consequence: "Double-charging customers is the classic failure of naive billing.",
    },
    {
      id: "bl-8",
      question: "How and when is tax determined?",
      options: ["Billing address at invoice time", "Address captured at signup", "No tax handling"],
      discriminator: "A customer moves country between signup and renewal.",
      category: "temporal",
      consequence: "Determines whether address history must be kept.",
    },
    {
      id: "bl-9",
      question: "Can an issued invoice be edited?",
      options: ["Immutable, corrected by credit note", "Editable in place", "Editable before payment only"],
      discriminator: "An invoice was issued with the wrong amount and has already been sent.",
      category: "reversal",
      consequence: "Immutability plus credit notes is a different data model from mutable invoices.",
    },
    {
      id: "bl-10",
      question: "Who is allowed to change the plan or see billing details?",
      options: ["Owners only", "Any member", "Owners and a billing role"],
      discriminator: "A regular team member opens the billing page.",
      category: "authority",
      consequence: "Billing is the most common place where a flat permission model breaks.",
    },
    {
      id: "bl-11",
      question: "What happens if a customer changes plan while a payment is failing?",
      options: ["Refused until settled", "Allowed and the debt is carried over", "Allowed and the debt is written off"],
      discriminator: "A customer in dunning tries to downgrade to the cheapest plan.",
      category: "concurrency",
      consequence: "Without a rule this becomes a way to escape an unpaid balance.",
    },
    {
      id: "bl-12",
      question: "On which date is a subscription charged?",
      options: ["The signup anniversary", "The first of the month for everyone", "A date the customer chooses"],
      discriminator: "A customer signs up on the 31st of January.",
      category: "boundary",
      consequence: "Anniversary billing has to answer what happens in months without that day.",
    },
  ],
};

const commerce: CorpusCase = {
  id: "commerce-checkout",
  domain: "commerce",
  request:
    "Build the checkout for our online shop. Customers add items to a basket, pay by card, and we send them " +
    "a confirmation email. We need to keep stock levels accurate.",
  fullSpec: [
    "Stock is reserved when checkout begins and the reservation expires after 15 minutes.",
    "If two customers reach checkout for the last unit, the first to reserve holds it and the second is told before payment, not after.",
    "Payment authorisation and stock decrement are one atomic outcome: if either fails, neither stands.",
    "If the confirmation email fails to send, the order is still valid and the email is retried.",
    "Overselling is never permitted and back-orders are not supported.",
    "A basket survives session loss for 30 days for signed-in customers and is not kept for guests.",
    "Prices are captured at the moment of payment, not when the item entered the basket.",
    "A repeated payment submission for the same basket does not create a second order.",
    "Refunds return stock only when the returned item is physically received, not when the refund is issued.",
    "A product removed from the catalogue while in a basket cannot be purchased and is flagged in the basket.",
    "Only the customer who owns an order may view it; support staff may view any order with the reason recorded.",
    "Guests may check out without an account, and a guest order can later be claimed by an account with the same email.",
  ].join("\n"),
  decisions: [
    {
      id: "cm-1",
      question: "When is stock reserved, and for how long?",
      options: ["At payment only", "At checkout start with a timeout", "When added to the basket"],
      discriminator: "A customer starts checkout for the last unit and pauses for 20 minutes.",
      category: "concurrency",
      consequence: "Reservation is a state machine with expiry; payment-time locking is not.",
    },
    {
      id: "cm-2",
      question: "What happens when two customers race for the last unit?",
      options: [
        "The loser is told before paying",
        "The loser is told after paying and refunded",
        "Both are sold and one is back-ordered",
      ],
      discriminator: "Two customers check out the last unit seconds apart.",
      category: "concurrency",
      consequence: "Decides whether the shop can oversell.",
    },
    {
      id: "cm-3",
      question: "If payment succeeds but the stock decrement fails, what stands?",
      options: [
        "Neither, the outcome is atomic",
        "The order stands and stock goes negative",
        "The payment is kept and the order is handled manually",
      ],
      discriminator: "The card is charged and the inventory write then fails.",
      category: "partial_failure",
      consequence: "This is where money and goods diverge if the question is left open.",
    },
    {
      id: "cm-4",
      question: "If the confirmation email fails, is the order still valid?",
      options: ["Valid, the email is retried", "The order is rolled back", "The order is held pending"],
      discriminator: "The mail provider is down at the moment the order completes.",
      category: "partial_failure",
      consequence: "Coupling notification to order validity is a common and costly mistake.",
    },
    {
      id: "cm-5",
      question: "Which price applies: the one when the item entered the basket, or at payment?",
      options: ["The price at payment", "The price when added", "The lower of the two"],
      discriminator: "The price of an item rises while it sits in a basket for a week.",
      category: "temporal",
      consequence: "Determines whether the basket stores prices or references them.",
    },
    {
      id: "cm-6",
      question: "How long does a basket survive, and does that differ for guests?",
      options: ["Session only", "Persisted for signed-in customers, not for guests", "Persisted for everyone"],
      discriminator: "A signed-in customer returns two weeks later on another device.",
      category: "lifecycle",
      consequence: "Turns the basket from client state into stored state.",
    },
    {
      id: "cm-7",
      question: "Does a repeated payment submission create a second order?",
      options: ["No, it is idempotent", "Yes", "It is blocked by a user interface guard only"],
      discriminator: "The customer refreshes the payment page after a slow response.",
      category: "idempotency",
      consequence: "Duplicate orders and duplicate charges are the same bug.",
    },
    {
      id: "cm-8",
      question: "When does a refunded item return to sellable stock?",
      options: ["On physical receipt", "When the refund is issued", "Never, it is handled manually"],
      discriminator: "A refund is issued while the item is still in transit back.",
      category: "reversal",
      consequence: "Returning stock when the refund is issued causes phantom inventory.",
    },
    {
      id: "cm-9",
      question: "What happens to a basket item that is withdrawn from the catalogue?",
      options: ["Blocked and flagged in the basket", "Silently removed", "Still purchasable"],
      discriminator: "A product is discontinued while sitting in the baskets of many customers.",
      category: "lifecycle",
      consequence: "Determines whether the basket revalidates against the catalogue.",
    },
    {
      id: "cm-10",
      question: "Who may view an order?",
      options: ["The owner only, and staff with a recorded reason", "The owner only", "Anyone holding the link"],
      discriminator: "A support agent opens the order of a customer to answer a query.",
      category: "authority",
      consequence: "Order data is personal data; access needs a rule and an audit trail.",
    },
    {
      id: "cm-11",
      question: "May customers check out without an account, and what happens to that order later?",
      options: ["Guest checkout, claimable later", "An account is required", "Guest checkout, never claimable"],
      discriminator: "A guest orders, then registers with the same email address.",
      category: "boundary",
      consequence: "Identity linkage is a data model decision made at checkout time.",
    },
    {
      id: "cm-12",
      question: "Is overselling ever acceptable?",
      options: ["Never", "Yes, with a back-order", "Yes for selected product lines"],
      discriminator: "Demand exceeds stock during a promotion.",
      category: "boundary",
      consequence: "Back-orders introduce an entirely separate fulfilment state.",
    },
  ],
};

const approval: CorpusCase = {
  id: "approval-expenses",
  domain: "approval",
  request:
    "Build an expense approval tool. Employees submit expenses with a receipt, their manager approves or " +
    "rejects them, and approved expenses go to finance for payment.",
  fullSpec: [
    "An expense above 500 requires a second approval from finance; below that the manager alone is sufficient.",
    "An employee may never approve their own expense, including when they are acting as their own manager.",
    "If the manager of an employee is unset or has left, the request escalates to the manager of that manager.",
    "An approver who does not respond within 5 working days triggers a reminder, and after 10 the request escalates.",
    "A submitter may edit an expense only while it is in draft; editing an approved expense is not possible and a correction is a new submission.",
    "An approved expense may be recalled by finance before payment, which returns it to the submitter with a reason.",
    "Approvals are recorded with approver identity and timestamp and are immutable.",
    "Expenses are submitted in the currency of the receipt and converted at the rate on the date of submission.",
    "A rejected expense may be resubmitted once; a second rejection closes it permanently.",
    "Employees see only their own expenses; managers see their direct reports; finance sees everything.",
    "When an employee leaves, their in-flight expenses continue through approval and are paid to their recorded account.",
    "Duplicate receipts, detected by amount, date and vendor, are flagged for the approver but not blocked.",
  ].join("\n"),
  decisions: [
    {
      id: "ap-1",
      question: "Does the approval chain depend on the amount?",
      options: [
        "A single approver regardless",
        "A threshold triggers a second approver",
        "Every expense needs finance",
      ],
      discriminator: "An employee submits an expense far larger than usual.",
      category: "authority",
      consequence: "Turns approval from a single step into a routed workflow.",
    },
    {
      id: "ap-2",
      question: "Can somebody approve their own expense?",
      options: ["Never, it escalates", "Yes if they are senior enough", "Yes when they have no manager"],
      discriminator: "The head of a department, who has no manager in the system, submits an expense.",
      category: "authority",
      consequence: "Self-approval is the single most common control failure in expense systems.",
    },
    {
      id: "ap-3",
      question: "What happens when the approver of a request is unset or has left the company?",
      options: ["Escalate to the next level up", "The request stalls", "Anyone in finance may approve"],
      discriminator: "An employee submits an expense the day after their manager resigns.",
      category: "lifecycle",
      consequence: "Without a rule, requests silently stall forever.",
    },
    {
      id: "ap-4",
      question: "What happens when an approver simply does not respond?",
      options: ["Reminder then escalation", "Nothing, it waits", "Auto-approve after a period"],
      discriminator: "A request sits unopened for two weeks.",
      category: "temporal",
      consequence: "Determines whether the system has scheduled work at all.",
    },
    {
      id: "ap-5",
      question: "May a submitted expense be edited, and by whom?",
      options: ["Only while in draft", "At any time before payment", "Never after creation"],
      discriminator: "A submitter changes the amount after the manager has approved it.",
      category: "reversal",
      consequence: "Editing after approval invalidates the approval that was given.",
    },
    {
      id: "ap-6",
      question: "Can an approved expense be pulled back before it is paid?",
      options: ["Yes, by finance, with a reason", "No, approval is final", "Yes, by anyone in the chain"],
      discriminator: "Finance spots a problem with an approved expense before the payment run.",
      category: "reversal",
      consequence: "Adds a state between approved and paid.",
    },
    {
      id: "ap-7",
      question: "In which currency is an expense recorded, and at which exchange rate?",
      options: ["Receipt currency, rate at submission", "Company currency, entered manually", "Rate at payment date"],
      discriminator: "An employee submits a receipt in a foreign currency and it is paid three weeks later.",
      category: "money",
      consequence: "The rate date determines who absorbs the currency movement.",
    },
    {
      id: "ap-8",
      question: "What happens after a rejection?",
      options: ["Resubmit once, then closed", "Unlimited resubmission", "Rejection is final"],
      discriminator: "An employee fixes and resubmits a rejected expense for the third time.",
      category: "reversal",
      consequence: "Without a limit, rejection is not an outcome, only a delay.",
    },
    {
      id: "ap-9",
      question: "Who can see which expenses?",
      options: ["Own, reports, and finance sees all", "Everyone sees everything", "Only finance sees anything"],
      discriminator: "A manager opens the expense list.",
      category: "visibility",
      consequence: "Expense data reveals salary-adjacent and medical information.",
    },
    {
      id: "ap-10",
      question: "What happens to in-flight expenses when an employee leaves?",
      options: ["Continue and pay to the recorded account", "Cancelled", "Frozen for manual handling"],
      discriminator: "An employee resigns with three expenses awaiting approval.",
      category: "lifecycle",
      consequence: "Deactivating a user must not orphan money owed to them.",
    },
    {
      id: "ap-11",
      question: "Are duplicate submissions of the same receipt detected?",
      options: ["Flagged for the approver", "Blocked outright", "Not detected"],
      discriminator: "The same receipt is submitted twice, a month apart.",
      category: "idempotency",
      consequence: "Duplicate reimbursement is the main fraud vector in this domain.",
    },
    {
      id: "ap-12",
      question: "Is the approval record itself changeable?",
      options: ["Immutable with identity and timestamp", "Editable by finance", "Not recorded separately"],
      discriminator: "An auditor asks who approved a payment two years ago.",
      category: "authority",
      consequence: "The approval record is the audit artifact; if it is mutable it proves nothing.",
    },
  ],
};

const access: CorpusCase = {
  id: "access-document-sharing",
  domain: "access",
  request:
    "We want document sharing in our app. Users can share a document with other people, set whether they can " +
    "view or edit, and revoke access later.",
  fullSpec: [
    "Revoking access ends the ability to open the document immediately, including for sessions already open.",
    "A user who had edit access keeps authorship of the edits they already made; revocation is not retroactive to content.",
    "Sharing with a person who has no account creates a pending invitation that grants nothing until accepted.",
    "Access may be granted to an individual or to a group, and group membership changes take effect immediately.",
    "A link share is a distinct mechanism from a person share and may be disabled independently.",
    "When the owner of a document leaves the organisation, ownership transfers to their manager rather than being deleted.",
    "Deleting a document revokes all shares and moves it to a recoverable state for 30 days.",
    "A viewer may not see who else the document is shared with; an editor may.",
    "Downloading or copying content cannot be prevented and the product does not claim it can.",
    "An editor may not re-share the document; only the owner may grant access.",
    "Access changes are written to an audit log with actor, subject, permission and time.",
    "If a document is shared and then moved into a folder with different permissions, explicit shares win over inherited ones.",
  ].join("\n"),
  decisions: [
    {
      id: "ac-1",
      question: "When access is revoked, what happens to a session that already has the document open?",
      options: ["Access ends immediately", "It ends at next open", "The session continues until it expires"],
      discriminator: "A user has the document open when their access is revoked.",
      category: "concurrency",
      consequence: "Immediate revocation requires live permission checks, not just a check at open.",
    },
    {
      id: "ac-2",
      question: "Is revocation retroactive to content the person already created?",
      options: ["No, their edits remain", "Yes, their edits are removed", "Their edits are anonymised"],
      discriminator: "An editor is removed after making substantial edits.",
      category: "reversal",
      consequence: "Confusing access with authorship destroys work.",
    },
    {
      id: "ac-3",
      question: "What happens when a document is shared with someone who has no account?",
      options: ["A pending invitation granting nothing", "An account is created for them", "Sharing fails"],
      discriminator: "A user shares with an email address that is not registered.",
      category: "lifecycle",
      consequence: "Introduces an invitation entity distinct from a grant.",
    },
    {
      id: "ac-4",
      question: "Can access be granted to a group, and when do membership changes take effect?",
      options: ["Groups supported, effective immediately", "Individuals only", "Groups snapshot at share time"],
      discriminator: "Somebody joins a group that already has access to the document.",
      category: "authority",
      consequence: "Group grants are evaluated at access time rather than stored per person.",
    },
    {
      id: "ac-5",
      question: "Is a shareable link a separate mechanism from sharing with a person?",
      options: ["Separate and independently disabled", "The same mechanism", "No link sharing"],
      discriminator: "The owner revokes all people but a link is still circulating.",
      category: "visibility",
      consequence: "The classic leak is a live link after all named access is removed.",
    },
    {
      id: "ac-6",
      question: "What happens to documents when their owner leaves the organisation?",
      options: ["Ownership transfers", "Documents are deleted", "Documents become ownerless"],
      discriminator: "The only owner of a document leaves the company.",
      category: "lifecycle",
      consequence: "Ownerless documents are unrecoverable and unmanageable.",
    },
    {
      id: "ac-7",
      question: "What does deleting a document do to its shares, and is deletion reversible?",
      options: ["Revokes all shares, recoverable for a window", "Permanent immediately", "Shares survive deletion"],
      discriminator: "An owner deletes a document that ten people can currently open.",
      category: "reversal",
      consequence: "A recovery window is a different data model from a hard delete.",
    },
    {
      id: "ac-8",
      question: "Can a viewer see who else the document is shared with?",
      options: ["No, only editors can", "Everyone can", "Nobody but the owner can"],
      discriminator: "A viewer opens the sharing panel.",
      category: "visibility",
      consequence: "The recipient list is itself personal data about third parties.",
    },
    {
      id: "ac-9",
      question: "May a person with edit access share the document onward?",
      options: ["No, only the owner grants access", "Yes, editors may re-share", "Yes, with owner approval"],
      discriminator: "An editor forwards access to a colleague.",
      category: "authority",
      consequence: "Transitive sharing makes the access set unbounded and unauditable.",
    },
    {
      id: "ac-10",
      question: "Are access changes recorded, and with what detail?",
      options: ["Audit log with actor, subject, permission, time", "Not recorded", "Only the current state is kept"],
      discriminator: "Somebody asks how an external party got access last quarter.",
      category: "authority",
      consequence: "Without a log the question is unanswerable after the fact.",
    },
    {
      id: "ac-11",
      question: "When explicit shares and inherited folder permissions conflict, which wins?",
      options: ["Explicit wins", "Inherited wins", "The most restrictive wins"],
      discriminator: "A shared document is moved into a private folder.",
      category: "boundary",
      consequence: "Permission composition is where access control silently leaks or over-blocks.",
    },
    {
      id: "ac-12",
      question: "Does view-only access prevent downloading or copying?",
      options: ["No, and the product does not claim it does", "Yes, downloads are blocked", "Yes, copying is blocked"],
      discriminator: "A viewer selects all the text and pastes it elsewhere.",
      category: "boundary",
      consequence: "Promising uncopyable content is a promise the platform cannot keep.",
    },
  ],
};

const inventory: CorpusCase = {
  id: "inventory-stock-transfer",
  domain: "inventory",
  request:
    "Build stock management for our warehouses. Staff can move stock between warehouses, record what arrives " +
    "from suppliers, and see current stock levels per location.",
  fullSpec: [
    "A transfer has three states: dispatched, in transit and received, and stock belongs to neither location while in transit.",
    "A transfer that is never received is flagged after 14 days and investigated as shrinkage rather than silently written off.",
    "Received quantities may differ from dispatched quantities and the discrepancy is recorded, not overwritten.",
    "Stock levels may never go negative; a movement that would do so is rejected.",
    "Counting adjustments require a reason code and are separate from movements.",
    "Two staff recording a movement of the same stock at once are serialised; the second sees the updated level.",
    "Goods received without a matching purchase order are held in a quarantine location until reconciled.",
    "Stock levels are per location and per stock-keeping unit, and a unit may exist in multiple locations.",
    "Historical stock levels are reconstructible from the movement ledger; the level itself is derived, not authoritative.",
    "Staff may only move stock in warehouses they are assigned to; managers may move any.",
    "A cancelled transfer returns stock to the origin only if it has not been dispatched.",
    "Units of measure are fixed per stock-keeping unit and conversions are not permitted at movement time.",
  ].join("\n"),
  decisions: [
    {
      id: "iv-1",
      question: "Where does stock live while it is being moved between warehouses?",
      options: [
        "In a transit state belonging to neither",
        "Deducted at dispatch and added at receipt",
        "Still at the origin until received",
      ],
      discriminator: "A shipment leaves on Monday and arrives on Thursday; the level is checked on Tuesday.",
      category: "partial_failure",
      consequence: "Without a transit state, stock either disappears or is double-counted for days.",
    },
    {
      id: "iv-2",
      question: "What happens to a transfer that is dispatched but never received?",
      options: ["Flagged after a period and investigated", "Written off automatically", "Stays open forever"],
      discriminator: "A shipment is dispatched and no receipt is ever recorded.",
      category: "lifecycle",
      consequence: "Open transfers are how inventory quietly becomes wrong.",
    },
    {
      id: "iv-3",
      question: "What happens when the received quantity differs from the dispatched quantity?",
      options: ["Discrepancy recorded separately", "Received overwrites dispatched", "Receipt is rejected"],
      discriminator: "Ten units are dispatched and nine arrive.",
      category: "boundary",
      consequence: "Overwriting hides loss; recording it makes loss measurable.",
    },
    {
      id: "iv-4",
      question: "May a stock level go negative?",
      options: ["Never, the movement is rejected", "Yes, corrected later", "Yes, with a warning"],
      discriminator: "Somebody records a sale of 5 units when the system shows 3.",
      category: "boundary",
      consequence: "Negative stock is either an invariant or an accepted reality; the two designs differ.",
    },
    {
      id: "iv-5",
      question: "Are manual count adjustments the same thing as movements?",
      options: ["Separate, and require a reason code", "The same as a movement", "Direct edits to the level"],
      discriminator: "A physical count finds two units more than the system shows.",
      category: "authority",
      consequence: "Allowing direct edits destroys the audit trail that makes stock trustworthy.",
    },
    {
      id: "iv-6",
      question: "What happens when two staff record a movement of the same stock at the same time?",
      options: ["Serialised, the second sees the new level", "Last write wins", "Both applied blindly"],
      discriminator: "Two handheld scanners submit movements for the same unit simultaneously.",
      category: "concurrency",
      consequence: "This is the difference between a ledger and a mutable counter.",
    },
    {
      id: "iv-7",
      question: "What happens to goods that arrive without a matching purchase order?",
      options: ["Quarantined until reconciled", "Received into normal stock", "Rejected at the door"],
      discriminator: "A supplier delivers a pallet nobody ordered.",
      category: "partial_failure",
      consequence: "Introduces a quarantine location and a reconciliation process.",
    },
    {
      id: "iv-8",
      question: "Is the current stock level authoritative, or derived from a movement ledger?",
      options: ["Derived from the ledger", "The stored level is authoritative", "Both, reconciled nightly"],
      discriminator: "Somebody asks what the stock level was six weeks ago.",
      category: "temporal",
      consequence: "Only a ledger can answer historical questions or explain a discrepancy.",
    },
    {
      id: "iv-9",
      question: "Which warehouses may a given member of staff move stock in?",
      options: ["Only those they are assigned to", "Any warehouse", "Any, with approval"],
      discriminator: "A member of staff at one site records a movement at another site.",
      category: "authority",
      consequence: "Location scoping is an access rule, not a user interface filter.",
    },
    {
      id: "iv-10",
      question: "Can a transfer be cancelled, and does that depend on its state?",
      options: ["Only before dispatch", "At any time", "Never"],
      discriminator: "A transfer is cancelled while the lorry is on the road.",
      category: "reversal",
      consequence: "Cancelling a dispatched transfer would create stock that is nowhere.",
    },
    {
      id: "iv-11",
      question: "Can a stock-keeping unit be recorded in different units of measure?",
      options: ["Fixed per unit, no conversion at movement", "Converted at movement time", "Free text units"],
      discriminator: "One site counts in boxes and another in individual items.",
      category: "boundary",
      consequence: "Unit mismatches silently multiply or divide inventory by the case size.",
    },
    {
      id: "iv-12",
      question: "Can the same stock-keeping unit exist in several locations at once?",
      options: ["Yes, levels are per location", "One location per unit", "A single global level"],
      discriminator: "The same product is held at three warehouses.",
      category: "visibility",
      consequence: "A global level cannot answer whether an order can be fulfilled from a given site.",
    },
  ],
};

export const CORPUS: CorpusCase[] = [booking, billing, commerce, approval, access, inventory];

export function caseById(id: string): CorpusCase | undefined {
  return CORPUS.find((entry) => entry.id === id);
}
