import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { loadVerifyEnvironment, saveVerifyEnvironment } from "./environment";

const tempDirs: string[] = [];

function makeTempDir(prefix: string): string {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  tempDirs.push(dir);
  return dir;
}

afterEach(() => {
  for (const dir of tempDirs.splice(0)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }
});

describe("verify environment manifest", () => {
  it("loads a root environment.json manifest and normalizes sandbox settings", () => {
    const dir = makeTempDir("shelra-verify-env-");
    fs.writeFileSync(
      path.join(dir, "environment.json"),
      JSON.stringify(
        {
          ecosystem: "node",
          appKind: "nextjs",
          appLabel: "Demo app",
          install: ["npm ci"],
          build: ["npm run build"],
          start: "npm run start",
          startPort: "3000",
          smokeKind: "http",
          sandbox: {
            from: "verify-node-web",
            verifyBaseFrom: "verify-node-web-base",
            shellInit: ["export FOO=bar"],
          },
        },
        null,
        2,
      ),
    );

    const loaded = loadVerifyEnvironment(dir, { allowNet: true });
    expect(loaded?.path).toBe(path.join(dir, "environment.json"));
    expect(loaded?.recipe.installCommands).toEqual(["npm ci"]);
    expect(loaded?.recipe.buildCommands).toEqual(["npm run build"]);
    expect(loaded?.recipe.startCommand).toBe("npm run start");
    expect(loaded?.sandboxSettings.from).toBe("verify-node-web");
    expect(loaded?.sandboxSettings.verifyBaseFrom).toBe("verify-node-web-base");
    expect(loaded?.sandboxSettings.shellInit).toEqual(["export FOO=bar"]);
    expect(loaded?.sandboxSettings.allowNet).toBe(true);
  });

  it("prefers .shelra/environment.json over the root manifest", () => {
    const dir = makeTempDir("shelra-verify-env-precedence-");
    fs.writeFileSync(
      path.join(dir, "environment.json"),
      JSON.stringify({
        ecosystem: "node",
        appKind: "vite",
        appLabel: "Root",
        install: ["npm install"],
        smokeKind: "none",
      }),
    );
    fs.mkdirSync(path.join(dir, ".shelra"));
    fs.writeFileSync(
      path.join(dir, ".shelra", "environment.json"),
      JSON.stringify({
        ecosystem: "node",
        appKind: "nextjs",
        appLabel: "Nested",
        install: ["npm ci"],
        smokeKind: "none",
      }),
    );

    const loaded = loadVerifyEnvironment(dir);
    expect(loaded?.path).toBe(path.join(dir, ".shelra", "environment.json"));
    expect(loaded?.recipe.appKind).toBe("nextjs");
    expect(loaded?.recipe.installCommands).toEqual(["npm ci"]);
  });

  it("writes a generated .shelra/environment.json manifest", () => {
    const dir = makeTempDir("shelra-verify-env-write-");
    const written = saveVerifyEnvironment(
      dir,
      {
        ecosystem: "node",
        appKind: "nextjs",
        appLabel: "Generated app",
        shellInitCommands: ["export DEBIAN_FRONTEND=noninteractive"],
        bootstrapCommands: ["apt-get update"],
        installCommands: ["npm ci"],
        buildCommands: ["npm run build"],
        testCommands: ["npm run lint"],
        startCommand: "npm run start",
        startPort: "3000",
        smokeKind: "http",
        smokeTarget: "http://127.0.0.1:3000",
        evidence: ["Detected package.json"],
        notes: ["Generated by verify"],
      },
      { verifyBaseFrom: "verify-node-web", ports: ["3000:3000"], allowEphemeralInstall: true },
    );

    expect(written).toBe(path.join(dir, ".shelra", "environment.json"));
    const loaded = loadVerifyEnvironment(dir);
    expect(loaded?.path).toBe(written);
    expect(loaded?.recipe.installCommands).toEqual(["npm ci"]);
    expect(loaded?.sandboxSettings.verifyBaseFrom).toBe("verify-node-web");
    expect(loaded?.sandboxSettings.ports).toEqual(["3000:3000"]);
    expect(loaded?.sandboxSettings.allowEphemeralInstall).toBeUndefined();
  });
});
