import { expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { runTestsTool, shellTool } from "../../src/tools/workspace.js";

test("RunTests returns a structured verification result for a passing command", async () => {
  const result = await runTestsTool.execute(
    { command: "bun --version" },
    {
      root: process.cwd(),
      permissionMode: "EDIT",
      signal: new AbortController().signal,
      env: process.env,
    },
  );

  expect(result.exitCode).toBe(0);
  expect(result.command).toBe("bun --version");
  expect(result.failures).toEqual([]);
  expect(result.durationMs).toBeGreaterThanOrEqual(0);
  expect(result.output).toContain("1.3");
});

test("RunTests preserves concise failure evidence for a failing command", async () => {
  const result = await runTestsTool.execute(
    { command: "cmd /c exit 1" },
    {
      root: process.cwd(),
      permissionMode: "EDIT",
      signal: new AbortController().signal,
      env: process.env,
    },
  );

  expect(result.exitCode).not.toBe(0);
  expect(result.failures.length).toBeGreaterThan(0);
});

test("RunTests without arguments uses the host-discovered project command", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "shelra-tests-default-"));
  try {
    const result = await runTestsTool.execute(
      {},
      {
        root,
        permissionMode: "EDIT",
        signal: new AbortController().signal,
        env: process.env,
        defaultTestCommand: `bun -e "console.log('project-default-ok')"`,
      },
    );

    expect(result.exitCode).toBe(0);
    expect(result.command).toContain("project-default-ok");
    expect(result.output).toContain("project-default-ok");
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("Shell returns host-owned command, cwd, timing and timeout evidence", async () => {
  const result = await shellTool.execute(
    { command: "cmd /c echo hello" },
    {
      root: process.cwd(),
      permissionMode: "EDIT",
      signal: new AbortController().signal,
      env: process.env,
    },
  );

  expect(result.command).toBe("cmd /c echo hello");
  expect(result.cwd).toBe(process.cwd());
  expect(result.exitCode).toBe(0);
  expect(result.stdout.toLowerCase()).toContain("hello");
  expect(result.durationMs).toBeGreaterThanOrEqual(0);
  expect(result.timedOut).toBe(false);
});

test("Shell preserves quoted inline scripts generated by coding models", async () => {
  const context = {
    root: process.cwd(),
    permissionMode: "EDIT" as const,
    signal: new AbortController().signal,
    env: process.env,
  };

  const doubleQuoted = await shellTool.execute(
    { command: `bun -e "console.log('double-wrapper-ok')"` },
    context,
  );
  const singleQuoted = await shellTool.execute(
    { command: `bun -e 'console.log("single-wrapper-ok")'` },
    context,
  );

  expect(doubleQuoted.exitCode).toBe(0);
  expect(doubleQuoted.stdout).toContain("double-wrapper-ok");
  expect(singleQuoted.exitCode).toBe(0);
  expect(singleQuoted.stdout).toContain("single-wrapper-ok");
});
